#!/bin/bash
printf "\n ============================================================\n"
printf "                     Setting up fzf\n"
printf "============================================================\n"


FZF_DEST="${HOME}/.config/fzf"
mkdir $FZF_DEST

# install
if $INSTALL; then
  printf "\t Installing fzf ...\n"
  mkdir -p ~/.fzf
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install --bin
fi

# change to the src directory so we can symlink the files
stow -t "$FZF_DEST" -d "${DOTFILES_HOME}/dotfiles" fzf

printf "====================fzf setup complete ====================\n"

unset FZF_DEST
cd "$DOTFILES_SETUP"

