# GitHub project configuration
# Config stored in ~/.config/gh-project/
GH_PROJECT_CONFIG_DIR="$HOME/.config/gh-project"
GH_PROJECT_CONFIG_FILE="$GH_PROJECT_CONFIG_DIR/config"
GH_PROJECT_FIELDS_FILE="$GH_PROJECT_CONFIG_DIR/fields.json"

# Runtime variables (loaded from config)
typeset -g GH_PROJECT_NUMBER=""
typeset -g GH_PROJECT_OWNER=""
typeset -g GH_PROJECT_NODE_ID=""
typeset -g GH_PROJECT_FIELDS=""

gh_project_setup() {
  # Check if gh CLI is available
  if ! command -v gh &> /dev/null; then
    echo "GitHub CLI (gh) is not installed." >&2
    return 1
  fi

  # Create config directory if it doesn't exist
  mkdir -p "$GH_PROJECT_CONFIG_DIR"

  # Prompt for project owner
  local owner=""
  if [[ -n "$GH_PROJECT_OWNER" ]]; then
    echo "Current project owner: $GH_PROJECT_OWNER"
    read -r "owner?Project owner (press enter to keep current): "
    [[ -z "$owner" ]] && owner="$GH_PROJECT_OWNER"
  else
    read -r "owner?Project owner (org or username): "
  fi

  if [[ -z "$owner" ]]; then
    echo "Project owner is required" >&2
    return 1
  fi

  # Prompt for project number
  local number=""
  if [[ -n "$GH_PROJECT_NUMBER" ]]; then
    echo "Current project number: $GH_PROJECT_NUMBER"
    read -r "number?Project number (press enter to keep current): "
    [[ -z "$number" ]] && number="$GH_PROJECT_NUMBER"
  else
    read -r "number?Project number: "
  fi

  if [[ -z "$number" ]]; then
    echo "Project number is required" >&2
    return 1
  fi

  echo "Fetching project metadata from GitHub..."

  # Fetch project node ID
  local node_id
  node_id=$(gh project view "$number" --owner "$owner" --format json 2>/dev/null | jq -r '.id')
  if [[ -z "$node_id" || "$node_id" == "null" ]]; then
    echo "Failed to fetch project. Check owner and number are correct." >&2
    return 1
  fi

  # Fetch field list
  local fields
  fields=$(gh project field-list "$number" --owner "$owner" --format json 2>/dev/null)
  if [[ -z "$fields" ]]; then
    echo "Failed to fetch project fields" >&2
    return 1
  fi

  # Write config file
  cat > "$GH_PROJECT_CONFIG_FILE" <<EOF
# GitHub Project Configuration
# Generated by gh_project_setup
GH_PROJECT_NUMBER="$number"
GH_PROJECT_OWNER="$owner"
GH_PROJECT_NODE_ID="$node_id"
EOF

  # Write fields file
  echo "$fields" > "$GH_PROJECT_FIELDS_FILE"

  # Load into current session
  GH_PROJECT_NUMBER="$number"
  GH_PROJECT_OWNER="$owner"
  GH_PROJECT_NODE_ID="$node_id"
  GH_PROJECT_FIELDS="$fields"

  echo "Configuration saved to $GH_PROJECT_CONFIG_DIR"
  echo "Available statuses:"
  echo "$fields" | jq -r '.fields[] | select(.name == "Status") | .options[].name' | sed 's/^/  - /'
}

gh_project_load() {
  # Load config from files if not already loaded
  if [[ -z "$GH_PROJECT_NUMBER" || -z "$GH_PROJECT_OWNER" ]]; then
    if [[ -f "$GH_PROJECT_CONFIG_FILE" ]]; then
      source "$GH_PROJECT_CONFIG_FILE"
    else
      echo "Project not configured. Run 'gh_project_setup' first." >&2
      return 1
    fi
  fi

  # Load fields if not already loaded
  if [[ -z "$GH_PROJECT_FIELDS" ]]; then
    if [[ -f "$GH_PROJECT_FIELDS_FILE" ]]; then
      GH_PROJECT_FIELDS=$(cat "$GH_PROJECT_FIELDS_FILE")
    else
      echo "Fields cache missing. Run 'gh_project_setup' to refresh." >&2
      return 1
    fi
  fi

  return 0
}

gh_project_refresh() {
  # Refresh the cached field list from GitHub
  if ! gh_project_load; then
    return 1
  fi

  echo "Refreshing project fields from GitHub..."

  local fields
  fields=$(gh project field-list "$GH_PROJECT_NUMBER" --owner "$GH_PROJECT_OWNER" --format json 2>/dev/null)
  if [[ -z "$fields" ]]; then
    echo "Failed to fetch project fields" >&2
    return 1
  fi

  # Update fields file and runtime variable
  echo "$fields" > "$GH_PROJECT_FIELDS_FILE"
  GH_PROJECT_FIELDS="$fields"

  echo "Fields cache updated"
  echo "Available statuses:"
  echo "$fields" | jq -r '.fields[] | select(.name == "Status") | .options[].name' | sed 's/^/  - /'
}

# Auto-load config on shell startup (silent)
[[ -f "$GH_PROJECT_CONFIG_FILE" ]] && source "$GH_PROJECT_CONFIG_FILE"
[[ -f "$GH_PROJECT_FIELDS_FILE" ]] && GH_PROJECT_FIELDS=$(cat "$GH_PROJECT_FIELDS_FILE")

prd() {
  local branch=$(current_branch)
  local args=("$@")
  local issue_number=""

  # Check if branch name starts with an integer (issue number)
  if [[ $branch =~ ^[0-9]+ ]]; then
    issue_number=$(echo "$branch" | grep -o '^[0-9]\+')
    local body_text=" Issue: #${issue_number}"

    # Add the body text to the arguments
    args+=("-b" "$body_text")
  fi

  if gh pr create -R="$GH_PROJECT_OWNER/monorepo" -B=main -t="$branch" "${args[@]}"; then
    # Move issue to Code Review if we have an issue number
    if [[ -n "$issue_number" ]]; then
      move_issue "$issue_number" "Code Review"
    fi
  fi
}

issues() {
  local start_claude=false

  # Parse arguments
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --claude)
        start_claude=true
        shift
        ;;
      *)
        shift
        ;;
    esac
  done

  # Check if gh CLI is available
  if ! command -v gh &> /dev/null; then
    echo "GitHub CLI (gh) is not installed. Please install it first."
    return 1
  fi

  # Check if we're in a git repository
  if ! git rev-parse --show-toplevel &>/dev/null; then
    echo "Not in a git repository"
    return 1
  fi

  # Get issues using gh and format them for fzf
  local selected_issue
  selected_issue=$(gh issue list --state open --limit 100 --json number,title,labels \
    --template '{{range .}}{{.number}}: {{.title}}{{"\n"}}{{end}}' | \
    $(fzf_prog) --preview 'gh issue view {1} --json body --template "{{.body}}"' \
    --preview-window=right:50%:wrap --header="Select an issue:")

  if [[ -z "$selected_issue" ]]; then
    echo "No issue selected"
    return 0
  fi

  # Extract issue number and title, then create branch name
  local issue_number=$(echo "$selected_issue" | sed 's/:.*$//')
  local issue_title=$(echo "$selected_issue" | sed 's/^[0-9]*: //')
  local sanitized_title=$(echo "$issue_title" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g')
  local branch_name="${issue_number}-${sanitized_title}"

  # Let user choose where to check out the issue
  local choice
  choice=$(printf "Current worktree\nNew worktree" | $(fzf_prog) --header="Where to check out issue #${issue_number}?")

  if [[ -z "$choice" ]]; then
    echo "No choice selected"
    return 0
  fi

  if [[ "$choice" == "Current worktree" ]]; then
    checkout_issue "$issue_number" "$branch_name"
  else
    new_wt "$branch_name" "$branch_name"
    # Assign myself and move to In Progress after worktree is created
    local my_username=$(gh api user --jq '.login')
    local is_assigned=$(gh issue view "$issue_number" --json assignees --jq ".assignees[].login | select(. == \"$my_username\")")
    if [[ -z "$is_assigned" ]]; then
      echo "Assigning myself to issue #$issue_number..."
      gh issue edit "$issue_number" --add-assignee @me
    fi
    move_issue "$issue_number" "In Progress"
  fi

  # Start Claude Code if requested
  if [[ "$start_claude" == true ]]; then
    claude_issue "$issue_number"
  fi
}

claude_issue() {
  local issue_number="$1"

  if [[ -z "$issue_number" ]]; then
    echo "Usage: claude_issue <issue_number>"
    return 1
  fi

  # Fetch issue title and body using --jq to avoid control character issues
  local issue_title
  local issue_body
  issue_title=$(gh issue view "$issue_number" --json title --jq '.title')
  issue_body=$(gh issue view "$issue_number" --json body --jq '.body')

  local prompt="Please help me solve this GitHub issue.

Issue #${issue_number}: ${issue_title}

Description:
${issue_body}

Please analyze the issue and implement a solution."
  claude "$prompt"
}

checkout_issue() {
  local issue_number="$1"
  local branch_name="$2"

  if [[ -z "$issue_number" || -z "$branch_name" ]]; then
    echo "Usage: checkout_issue <issue_number> <branch_name>"
    return 1
  fi

  # Check if I'm assigned to the issue, if not assign me
  local my_username=$(gh api user --jq '.login')
  local is_assigned=$(gh issue view "$issue_number" --json assignees --jq ".assignees[].login | select(. == \"$my_username\")")
  if [[ -z "$is_assigned" ]]; then
    echo "Assigning myself to issue #$issue_number..."
    gh issue edit "$issue_number" --add-assignee @me
  fi

  echo "Creating/checking out branch: $branch_name"

  # Check if branch already exists locally
  if git show-ref --verify --quiet refs/heads/"$branch_name"; then
    echo "Branch '$branch_name' already exists locally. Checking it out..."
    git checkout "$branch_name"
  # Check if branch exists on remote
  elif git show-ref --verify --quiet refs/remotes/origin/"$branch_name"; then
    echo "Branch '$branch_name' exists on remote. Checking it out..."
    git checkout -b "$branch_name" "origin/$branch_name"
  else
    echo "Creating new branch '$branch_name' off of main..."
    # Ensure we're on main and it's up to date
    git checkout main
    git pull origin main
    # Create new branch
    git checkout -b "$branch_name"
  fi

  # Move issue to In Progress
  move_issue "$issue_number" "In Progress"
}

staging_issues() {
  # Check if gh CLI is available
  if ! command -v gh &> /dev/null; then
    echo "GitHub CLI (gh) is not installed."
    return 1
  fi

  # Load project config
  if ! gh_project_load; then
    return 1
  fi

  # Get status field ID and Staging option ID from cached fields
  local status_field_id
  local staging_status_id
  status_field_id=$(echo "$GH_PROJECT_FIELDS" | jq -r '.fields[] | select(.name == "Status") | .id')
  staging_status_id=$(echo "$GH_PROJECT_FIELDS" | jq -r '.fields[] | select(.name == "Status") | .options[] | select(.name == "Staging") | .id')

  if [[ -z "$staging_status_id" || "$staging_status_id" == "null" ]]; then
    echo "Could not find 'Staging' status option"
    return 1
  fi

  # Get merged PRs authored by me from the last 2 days
  local two_days_ago=$(date -v-2d +%Y-%m-%d)
  echo "Fetching my merged PRs since $two_days_ago..."
  local merged_prs
  merged_prs=$(gh pr list --author @me --state merged --search "merged:>=$two_days_ago" --limit 50 --json number,title,mergedAt)

  local pr_count=$(echo "$merged_prs" | jq -r 'length')
  echo "Found $pr_count merged PRs"

  # Fetch all project items once (issue number, status, and item id)
  echo "Fetching project item statuses..."
  local project_items
  project_items=$(gh project item-list "$GH_PROJECT_NUMBER" --owner "$GH_PROJECT_OWNER" --limit 500 --format json \
    --jq '[.items[] | {number: .content.number, status: .status, id: .id}]' 2>/dev/null)

  # Arrays to track results
  local -a no_issue_prs=()
  local -a not_in_project=()
  local -a already_done=()
  local -a already_staging=()
  local -a moved_to_staging=()

  # Process each merged PR - extract issue number from title (format: "123-feature-name")
  local pr_lines=$(echo "$merged_prs" | jq -r '.[] | "\(.number) \(.title)"')
  while IFS= read -r line; do
    local pr_number=$(echo "$line" | awk '{print $1}')
    local pr_title=$(echo "$line" | cut -d' ' -f2-)

    # Extract issue number from PR title (assumes title starts with issue number)
    local issue_number
    issue_number=$(echo "$pr_title" | grep -o '^[0-9]\+' || true)

    if [[ -z "$issue_number" ]]; then
      no_issue_prs+=("PR #$pr_number")
      continue
    fi

    # Look up status and item id from cached project items
    local item_info
    item_info=$(echo "$project_items" | jq -r --arg num "$issue_number" '.[] | select(.number == ($num | tonumber))')
    local current_status=$(echo "$item_info" | jq -r '.status // empty')
    local item_id=$(echo "$item_info" | jq -r '.id // empty')

    if [[ -z "$item_id" ]]; then
      not_in_project+=("#$issue_number")
      continue
    fi

    if [[ "$current_status" == "Done" ]]; then
      already_done+=("#$issue_number")
      continue
    fi

    if [[ "$current_status" == "Staging" ]]; then
      already_staging+=("#$issue_number")
      continue
    fi

    # Move to staging
    gh project item-edit --id "$item_id" --project-id "$GH_PROJECT_NODE_ID" --field-id "$status_field_id" --single-select-option-id "$staging_status_id" >/dev/null
    moved_to_staging+=("#$issue_number")
  done <<< "$pr_lines"

  # Print summary
  echo ""
  echo "=== Summary ==="
  if [[ ${#moved_to_staging[@]} -gt 0 ]]; then
    echo "Moved to Staging (${#moved_to_staging[@]}): ${moved_to_staging[*]}"
  fi
  if [[ ${#already_staging[@]} -gt 0 ]]; then
    echo "Already Staging (${#already_staging[@]}): ${already_staging[*]}"
  fi
  if [[ ${#already_done[@]} -gt 0 ]]; then
    echo "Already Done (${#already_done[@]}): ${already_done[*]}"
  fi
  if [[ ${#not_in_project[@]} -gt 0 ]]; then
    echo "Not in project (${#not_in_project[@]}): ${not_in_project[*]}"
  fi
  if [[ ${#no_issue_prs[@]} -gt 0 ]]; then
    echo "No issue in title (${#no_issue_prs[@]}): ${no_issue_prs[*]}"
  fi
}

new_wt() {
  local name="$1"
  local branch="${2:-$name}"

  if [[ -z "$name" ]]; then
    echo "Usage: new_wt <worktree-name> [branch]"
    return 1
  fi

  # Check if we're in a git repository
  local current_worktree=$(git rev-parse --show-toplevel 2>/dev/null)
  if [[ -z "$current_worktree" ]]; then
    echo "Not in a git repository"
    return 1
  fi

  local worktree_path="../$name"

  # Check if branch already exists locally or remotely
  if git show-ref --verify --quiet refs/heads/"$branch"; then
    echo "Branch '$branch' exists locally. Creating worktree..."
    git worktree add "$worktree_path" "$branch"
  elif git show-ref --verify --quiet refs/remotes/origin/"$branch"; then
    echo "Branch '$branch' exists on remote. Creating worktree..."
    git worktree add "$worktree_path" "$branch"
  else
    echo "Creating new branch '$branch' off of main..."
    # Ensure main is up to date
    git fetch origin main
    git worktree add "$worktree_path" -b "$branch" origin/main
  fi

  # Try to copy .env file from any existing worktree
  local all_worktrees=$(git worktree list --porcelain | grep '^worktree ' | sed 's/^worktree //')
  local env_copied=false
  while IFS= read -r wt; do
    if [[ -f "$wt/.env" ]]; then
      cp "$wt/.env" "$worktree_path/"
      echo "Copied .env file from $wt"
      env_copied=true
      break
    fi
  done <<< "$all_worktrees"

  if [[ "$env_copied" == false ]]; then
    echo "No .env file found in any existing worktree"
  fi

  # Change to the new worktree directory
  cd "$worktree_path"
  echo "Changed to worktree directory: $(pwd)"

  # Run bun install
  echo "Running bun install..."
  bun install

  # For Samwise specifically
  bun run api:build-pdf
}

move_issue() {
  local issue_id="$1"
  local target_status="$2"

  if [[ -z "$issue_id" || -z "$target_status" ]]; then
    echo "Usage: move_issue <issue_number> <status>"
    echo "Example: move_issue 959 \"In Progress\""
    echo ""
    echo "Run 'gh_project_setup' to configure, or 'gh_project_refresh' to update statuses"
    return 1
  fi

  # Load project config
  if ! gh_project_load; then
    return 1
  fi

  # Get status field ID and target status option ID from cached fields
  local status_field_id
  local target_status_id
  status_field_id=$(echo "$GH_PROJECT_FIELDS" | jq -r '.fields[] | select(.name == "Status") | .id')
  target_status_id=$(echo "$GH_PROJECT_FIELDS" | jq -r --arg status "$target_status" '.fields[] | select(.name == "Status") | .options[] | select(.name == $status) | .id')

  if [[ -z "$target_status_id" || "$target_status_id" == "null" ]]; then
    echo "Invalid status: '$target_status'"
    echo "Available statuses:"
    echo "$GH_PROJECT_FIELDS" | jq -r '.fields[] | select(.name == "Status") | .options[].name' | sed 's/^/  - /'
    return 1
  fi

  # Get project item ID using gh's built-in --jq to avoid control character issues
  local project_item
  project_item=$(gh project item-list "$GH_PROJECT_NUMBER" --owner "$GH_PROJECT_OWNER" --limit 500 --format json \
    --jq ".items[] | select(.content.number == $issue_id) | .id" 2>/dev/null)

  if [[ -z "$project_item" || "$project_item" == "null" ]]; then
    echo "Issue #${issue_id} not found in project"
    return 1
  fi

  echo "Moving issue #${issue_id} to '${target_status}'..."

  # Edit the project item
  if gh project item-edit --id "$project_item" --project-id "$GH_PROJECT_NODE_ID" --field-id "$status_field_id" --single-select-option-id "$target_status_id"; then
    echo "Successfully moved issue #${issue_id} to '${target_status}'"
  else
    echo "Failed to move issue #${issue_id}"
    return 1
  fi
}
